### ISSUE TITLE
How to root A20e on the latest software?

### ISSUE THREAD

**Issue by KirChi123** [TBM13/Samsung-Camera-Experiments#1]
Hello! Please make a guide on how to root A20e the easiest way so that I can use this module because I dont want to risk bricking my phone.

**Comment by TBM13** [comment]
Try searching for guides in XDA.

**Comment by KirChi123** [comment]
All guides are for Android 9 or 8 but I have updated to 11 and am worrying because someone stated something about trigerring knox the security of the phone and then the phone not booting..

**Comment by TBM13** [comment]
You can ask for help in the A20/A20e [Telegram Group](https://t.me/Galaxy_A20_official)
