### ISSUE TITLE
libexynoscamera3.so files are non-existent

### ISSUE THREAD

**Issue by Sneezy123** [TBM13/Samsung-Camera-Experiments#10]
Device: Samsung Galaxy A54 5G

Problem:
When I go into the folder vendor/lib/ I can't find a file named "libexynoscamera3.so".

There is only 
libexynosdisplay.so
libexynosgraphicbuffer.so
libexynosgraphicbuffer_core.so
libexynosutils.so
libexynosv4l2.so

The path for this folder is "/vendor/lib"

**Comment by TBM13** [comment]
In that case there's nothing I can do. If you are using an explorer app to search for the lib make sure you gave it root access.

I believe someone else has reported this same thing for the A54 too so Samsung may have changed something
