### ISSUE TITLE
Please add support for m21(2020)

### ISSUE THREAD

**Issue by Sujalchhetri01** [TBM13/Samsung-Camera-Experiments#11]
When I tried to patch it, it gave this issue 
python patch_lib.py C:\libexynoscamera3.so C:\adb\libexynoscamera3.so -hw 1 -cap 16
[*] Patching 32-bit lib...
[*] [Modify ExynosCameraSensorInfo struct] Found match using "Exynos 850/9611 (Android 12-13) (32-bit)" pattern
ExynosCameraSensorInfo struct register: r7 Free register(s): r0
[*] [Find available capabilities & hardware level offsets] Found match using "Generic (32-bit)" pattern
Available capabilities offset: 0x648
Hardware level offset: 0x640
[+] Hardware level set to 1 (FULL)
[+] Enabled capabilities: RAW
[*] [Modify ExynosCameraSensorInfo struct] Found match using "Exynos 850/9611 (Android 12-13) (32-bit)" pattern
[+] Applied "Modify ExynosCameraSensorInfo struct"
[*] Patched lib saved as "libexynoscamera3_patched.so"

[*] Patching 64-bit lib...
[!] [Modify ExynosCameraSensorInfo struct] Unexpected number of matches (0)

**Comment by TBM13** [comment]
Send the libs

**Comment by Sujalchhetri01** [comment]
> Send the libs

**Comment by Sujalchhetri01** [comment]
> Send the libs
libs m21(2020)
[libsm21.zip](https://github.com/TBM13/Samsung-Camera-Experiments/files/15087562/libsm21.zip)

**Comment by Sujalchhetri01** [comment]
Can you do it faster, please?

**Comment by TBM13** [comment]
Should work fine now
