### ISSUE TITLE
Please create one for galaxy s10 latest firmware

### ISSUE THREAD

**Issue by Setifler19** [TBM13/Samsung-Camera-Experiments#12]
[lib s10.zip](https://github.com/TBM13/Samsung-Camera-Experiments/files/15122181/lib.s10.zip)

**Comment by TBM13** [comment]
Please use the Python script to do it yourself, it's not difficult. If some error appears, then you can open an issue here.

**Comment by TBM13** [comment]
Send the 64-bit lib too

**Comment by Setifler19** [comment]
> Send the 64-bit lib too

It doesn't exist in the latest firmware only the vendor/lib one

**Comment by TBM13** [comment]
[Module_S10.zip](https://github.com/TBM13/Samsung-Camera-Experiments/files/15173787/Module_S10.zip)
I'm guessing that creating a Magisk module with RAW enabled was what you wanted me to do
