### ISSUE TITLE
Galaxy A30s - patching 32-bit lib works while 64-bit fails

### ISSUE THREAD

**Issue by donut2008** [TBM13/Samsung-Camera-Experiments#15]
![image](https://github.com/user-attachments/assets/a1af2a4c-bd8b-4734-a96f-c1e96e3a086e)
Tried with the `-hw 1` flag, but that didn't work either.

**Comment by TBM13** [comment]
Please send the 64-bit lib and if possible tell me your firmware/vendor/Android version.

**Comment by donut2008** [comment]
[libexynoscamera3.zip](https://github.com/user-attachments/files/16315884/libexynoscamera3.zip)
Build number: RP1A.200720.012.A307FNXXU4CWH7
Android version: 11
One UI version: 3.1
August 2023 SPL

**Comment by TBM13** [comment]
Should work fine now.
