### ISSUE TITLE
[Android 13 support]?

### ISSUE THREAD

**Issue by Tuxino88** [TBM13/Samsung-Camera-Experiments#3]
https://sourceforge.net/projects/derpfest/files/a20e/

https://forum.xda-developers.com/t/rom-12-0-derpfest-for-galaxy-a20-a20e-official-a20-a20e.4369567/

**Comment by TBM13** [comment]
Android 13 is supported. The only requirement is a compatible kernel and vendor, which implies they need to use the stock Android 11 camera HAL
