### ISSUE TITLE
Add Note 20 Ultra 5G

### ISSUE THREAD

**Issue by dedsecproyt** [TBM13/Samsung-Camera-Experiments#4]
Can you add module for all works cameras for G-Cam ports [Link of G-Cam port](https://www.celsoazevedo.com/files/android/google-camera/dev-hasli/) 
Wide and frontal camera not works

**Comment by TBM13** [comment]
If you're still interested, send me your 32-bit (`/vendor/lib/libexynoscamera3.so`) and 64-bit (`/vendor/lib64/libexynoscamera3.so`) camera libraries and specify your Android/OneUI version (if you are on AOSP the Android version where your vendor comes from).
I'll close the issue for now.
