### ISSUE TITLE
Add A54 5G

### ISSUE THREAD

**Issue by TODDYNDOSVRAU** [TBM13/Samsung-Camera-Experiments#5]
Please

**Comment by TBM13** [comment]
If you're still interested, send me your 32-bit (`/vendor/lib/libexynoscamera3.so`) and 64-bit (`/vendor/lib64/libexynoscamera3.so`) camera libraries and specify your Android/OneUI version (if you are on AOSP the Android version where your vendor comes from).
I'll close the issue for now.
