### ISSUE TITLE
Add A34 5G

### ISSUE THREAD

**Issue by w0lzard** [TBM13/Samsung-Camera-Experiments#6]
This module doesn't work on Samsung Galaxy A34 5G

**Comment by TBM13** [comment]
That's my main phone right now and I still haven't figured out how to enable RAW capture on it. Anyway, this project is only for Exynos devices while the A34 is a MediaTek device

**Comment by w0lzard** [comment]
> That's my main phone right now and I still haven't figured out how to enable RAW capture on it. Anyway, this project is only for Exynos devices while the A34 is a MediaTek device

Oh my bad I didn't knew
