### ISSUE TITLE
Lib crashes after enabling RAW if the device has depth cameras

### ISSUE THREAD

**Issue by berkantdu123** [TBM13/Samsung-Camera-Experiments#7]
Please add support for S20 Ultra
Android version: Android 14/OneUI 6
Rom: ExtremeROM
CPU: Exynos990

Library /vendor/lib/:
https://gofile.io/d/OdoH2T
Library /vendor/lib64/:
https://gofile.io/d/T8eaVE

Direct link to both in .zip:
[library.zip](https://github.com/TBM13/Samsung-Camera-Experiments/files/13997671/library.zip)

Md5:
/vendor/lib/libexynoscamera3.so:
ac5d49828334cdc068ba78ea94365033
/vendor/lib64/libexynoscamera3.so:
ca361d2b42e4ff06e6ab034b0de58270

**Comment by TBM13** [comment]
The script should work with that lib now. Let me know if there is any other issue or if you test GCam so I can add the device to the README

**Comment by berkantdu123** [comment]
> The script should work with that lib now. Let me know if there is any other issue or if you test GCam so I can add the device to the README

Enabling raw bricks the camera2api on the s20u

**Comment by TBM13** [comment]
You mean that all cameras disappeared, right? That means the lib crashed, will take a look to it

**Comment by berkantdu123** [comment]
> You mean that all cameras disappeared, right? That means the lib crashed, will take a look to it
> 
> Just to make sure, did you install the modified lib in the same exact device you grabbed the libs from? Sometimes different devices (even if they have the same model) use a different version of the camera lib depending on the installed firmware version

I did yes, I'm using the exact same device I extracted the libs from, I can confirm that in camera2api probe theres no output, so the lib crashed. My guess is that it tries to give raw capabilities at the depth output camera (tof) so it crashes

**Comment by berkantdu123** [comment]
Any updates? I'm always here if you need any helps, logs or anything I can help you with, I'm really excited and full of hopes for this project
The s20+ exynos with patched libs has been confirmed fully working (front and rear cameras) with agc gcam in a telegram group, hopefully we will see the same for the s20u!
If you want a direct contact through either discord or telegram, you can contact me @hectarox 
@TBM13

**Comment by TBM13** [comment]
I took a quick look at your libs after patching them and I didn't find anything weird.
I doubt enabling RAW on the depth cameras is causing the issue, but still it's a possibility.

I'll try to manually edit the libs you sent here to only enable RAW on non-depth cameras and send them later

**Comment by berkantdu123** [comment]
> I took a quick look at your libs after patching them and I didn't find anything weird.
> I doubt enabling RAW on the depth cameras is causing the issue, but still it's a possibility.
> 
> I'll try to manually edit the libs you sent here to only enable RAW on non-depth cameras and send them later

Alright, I would love to test that!

**Comment by TBM13** [comment]
I haven't done it yet, but first I want to discard something else from being the issue so could you give these two libs a try?
[1.zip](https://github.com/TBM13/Samsung-Camera-Experiments/files/14269975/1.zip)

**Comment by berkantdu123** [comment]
> I haven't done it yet, but first I want to discard something else from being the issue so could you give these two libs a try? [1.zip](https://github.com/TBM13/Samsung-Camera-Experiments/files/14269975/1.zip)

Library crashes; no output on camera nor camera2api

**Comment by TBM13** [comment]
Could you send me a logcat from device startup to boot using the patched libs and another one using the original libs?

**Comment by berkantdu123** [comment]
> Could you send me a logcat from device startup to boot using the patched libs and another one using the original libs?

How can I do that? I have never done a logcat from startup to boot before

**Comment by TBM13** [comment]
> > Could you send me a logcat from device startup to boot using the patched libs and another one using the original libs?
> 
> How can I do that? I have never done a logcat from startup to boot before

Execute adb logcat on your PC, turn on your phone, connect it and stop taking the log once the lock screen appears

**Comment by berkantdu123** [comment]
[logcat_patched.txt](https://github.com/TBM13/Samsung-Camera-Experiments/files/14271091/logcat.txt)
This is with the modified lib, I will edit this message to add the original libs afterwards
The logcat starts with the crash report of the library, should be what you need

**Comment by berkantdu123** [comment]
And here is stock libs logcat
[logcat_stock_lib.txt](https://github.com/TBM13/Samsung-Camera-Experiments/files/14271174/logcat_stock_lib.txt)

**Comment by TBM13** [comment]
Yes, looking at the log has convinced me more that it may be caused by enabling RAW on the depth cameras.

[2.zip](https://github.com/TBM13/Samsung-Camera-Experiments/files/14274412/2.zip)
Give it a try and let me know. If I didn't make any mistake RAW shouldn't be enabled on the depth cameras now.

I did something quite messy, but just thought about something better to achieve the same (which could even be added to the Python script as an option). If those libs still don't work send me another logcat and I'll try to modify the libs again with this other method.

**Comment by berkantdu123** [comment]
> Yes, looking at the log has convinced me more that it may be caused by enabling RAW on the depth cameras.
> 
> [2.zip](https://github.com/TBM13/Samsung-Camera-Experiments/files/14274412/2.zip) Give it a try and let me know. If I didn't make any mistake RAW shouldn't be enabled on the depth cameras now.
> 
> I did something quite messy, but just thought about something better to achieve the same (which could even be added to the Python script as an option). If those libs still don't work send me another logcat and I'll try to modify the libs again with this other method.

It crashes again
[logcat_custom_lib.txt](https://github.com/TBM13/Samsung-Camera-Experiments/files/14278049/logcat_custom_lib.txt)
I can see this line that seems interesting
 02-14 11:02:28.736  7348  7348 F DEBUG   : Abort message: 'UniHal3Entry.cpp: GetVendorHalModule: 25: Failed to hw_get_module of CAMERA_HARDWARE_MODULE_ID by -22'

**Comment by TBM13** [comment]
`Could not load /vendor/lib64/hw/camera.exynos990.so from default namespace: dlopen failed: library "libexynoscamera3.so" not found: needed by /vendor/lib64/hw/camera.exynos990.so in namespace (default).`

Can you check you didn't accidentally delete the lib instead of replacing it?

**Comment by berkantdu123** [comment]
> `Could not load /vendor/lib64/hw/camera.exynos990.so from default namespace: dlopen failed: library "libexynoscamera3.so" not found: needed by /vendor/lib64/hw/camera.exynos990.so in namespace (default).`
> 
> Can you check you didn't accidentally delete the lib instead of replacing it?

I haven't touched my system since, and after verifying, the libs are where they're supposed to be
They also have correct permissions (644, rw-r--r--)

![Screenshot_20240216_192351_Solid Explorer.jpg](https://github.com/TBM13/Samsung-Camera-Experiments/assets/52573108/f6237af6-385e-4576-9024-7f684d77ffe9)

![Screenshot_20240216_192335_Solid Explorer.jpg](https://github.com/TBM13/Samsung-Camera-Experiments/assets/52573108/9bc17ce5-9031-4495-a553-9c7329284d49)

**Comment by berkantdu123** [comment]
> `Could not load /vendor/lib64/hw/camera.exynos990.so from default namespace: dlopen failed: library "libexynoscamera3.so" not found: needed by /vendor/lib64/hw/camera.exynos990.so in namespace (default).`
> 
> Can you check you didn't accidentally delete the lib instead of replacing it?

I also installed logfox and every 5s I get this crash when using my phone
![crash-_vendor_bin_hw_vendor-samsung-hardware-camera-provider@4-0-service_64-17_02-01-06-58_226.zip](https://github.com/TBM13/Samsung-Camera-Experiments/files/14317029/crash-_vendor_bin_hw_vendor-samsung-hardware-camera-provider%404-0-service_64-17_02-01-06-58_226.zip)

**Comment by berkantdu123** [comment]
> `Could not load /vendor/lib64/hw/camera.exynos990.so from default namespace: dlopen failed: library "libexynoscamera3.so" not found: needed by /vendor/lib64/hw/camera.exynos990.so in namespace (default).`
> 
> Can you check you didn't accidentally delete the lib instead of replacing it?

I RESOLVED THE ISSUE!!!
I copied the library to /vendor/lib64/hw/libexynoscamera3.so and it worked!!
Idk why I had to put it there, but now it works
Tysm!!!!

![Screenshot_20240217_012207_Camera2 Probe.jpg](https://github.com/TBM13/Samsung-Camera-Experiments/assets/52573108/b29bf8cb-e124-46ac-b661-8480892bd087)

![Screenshot_20240217_012216_Camera2 Probe.jpg](https://github.com/TBM13/Samsung-Camera-Experiments/assets/52573108/b69d3d95-28bb-4c3a-9f3a-3d80c896e70f)

**Comment by TBM13** [comment]
> I RESOLVED THE ISSUE!!!
I copied the (64bit) library to /vendor/lib64/hw/libexynoscamera3.so and it worked!!
Idk why I had to put it there, but now it works
Tysm!

That's really strange, but I'm happy to hear it works.

> I'll try patching with the script to see if it works, if it does, I'll mark as completed

Please do, and let me know

**Comment by berkantdu123** [comment]
> > I RESOLVED THE ISSUE!!!
> > I copied the (64bit) library to /vendor/lib64/hw/libexynoscamera3.so and it worked!!
> > Idk why I had to put it there, but now it works
> > Tysm!
> 
> That's really strange, but I'm happy to hear it works.
> 
> > I'll try patching with the script to see if it works, if it does, I'll mark as completed
> 
> Please do, and let me know

Hey, sorry to get back to you after all of these months, I had my exams. I just tried patching again and seems like it crashes after patching with the script, seems like there was 2 crashes in the original issue, one being because it patched the depth output camera, and the second one because it wasn't in /vendor/lib64/hw
Could be great if you could implement a fix so that it doesn't patch the depth output camera, I really appreciate your work, thank you very very much and still sorry for the huge delay

**Comment by TBM13** [comment]
> > > I RESOLVED THE ISSUE!!!
> > > I copied the (64bit) library to /vendor/lib64/hw/libexynoscamera3.so and it worked!!
> > > Idk why I had to put it there, but now it works
> > > Tysm!
> > 
> > 
> > That's really strange, but I'm happy to hear it works.
> > > I'll try patching with the script to see if it works, if it does, I'll mark as completed
> > 
> > 
> > Please do, and let me know
> 
> Hey, sorry to get back to you after all of these months, I had my exams. I just tried patching again and seems like it crashes after patching with the script, seems like there was 2 crashes in the original issue, one being because it patched the depth output camera, and the second one because it wasn't in /vendor/lib64/hw Could be great if you could implement a fix so that it doesn't patch the depth output camera, I really appreciate your work, thank you very very much and still sorry for the huge delay

Thanks for the feedback. Will try to implement the fix soon.
Btw, curious to hear if patching the lib was useful to you in some way (using GCam or anything like that)

**Comment by TBM13** [comment]
> Here there, @TBM13. Another S20U (SM-G988B, z3s) user here. I experience just the same issue.

The lib crash, the `dlopen failed: library "libexynoscamera3.so" not found` issue or both?

**Comment by TBM13** [comment]
@Emulond @berkantdu123 Please try patching your libs again with the new `--skip-depth` option and let me know if it works.

**Comment by berkantdu123** [comment]
> @Emulond @berkantdu123 Please try patching your libs again with the new `--skip-depth` option and let me know if it works.

Hey, sorry for the late reply, was busy. I tried, although I can't do full + capabilities because of "No space left" error when patching libs, only enabling capabilities worked and now front camera works again on gcam, have a better quality overall and unlocked features. Thank you very much.

**Comment by TBM13** [comment]
> > @Emulond @berkantdu123 Please try patching your libs again with the new `--skip-depth` option and let me know if it works.
> 
> Hey, sorry for the late reply, was busy. I tried, although I can't do full + capabilities because of "No space left" error when patching libs, only enabling capabilities worked and now front camera works again on gcam, have a better quality overall and unlocked features. Thank you very much.

Thanks for confirming. As for the "no space left" error, that's a limitation of the method I use to apply the modifications.

**Comment by Mdkhairul90** [comment]
> Please add support for S20 Ultra Android version: Android 14/OneUI 6 Rom: ExtremeROM CPU: Exynos990
> 
> Library /vendor/lib/: https://gofile.io/d/OdoH2T Library /vendor/lib64/: https://gofile.io/d/T8eaVE
> 
> Direct link to both in .zip: [library.zip](https://github.com/TBM13/Samsung-Camera-Experiments/files/13997671/library.zip)
> 
> Md5: /vendor/lib/libexynoscamera3.so: ac5d49828334cdc068ba78ea94365033 /vendor/lib64/libexynoscamera3.so: ca361d2b42e4ff06e6ab034b0de58270

https://github.com/TBM13/Samsung-Camera-Experiments/issues/7#issue-2092016355
