### ISSUE TITLE
Please add support for Galaxy Note20 Ultra

### ISSUE THREAD

**Issue by SusssyBakaLOL** [TBM13/Samsung-Camera-Experiments#8]
Rom: One UI 6.0 port from S21U by Igor
Kernel: ExtremeKernel
SoC: Exynos 990
Both lib64 and lib in zip
[exynos_note20ultra_oneui6.zip](https://github.com/TBM13/Samsung-Camera-Experiments/files/13998892/exynos_note20ultra_oneui6.zip)

**Comment by TBM13** [comment]
The script already supports those two libs
