### ISSUE TITLE
Please add support for Galaxy S20 LTE

### ISSUE THREAD

**Issue by SusssyBakaLOL** [TBM13/Samsung-Camera-Experiments#9]
Extreme Rom V3
Extreme Kernel
[S20lte.zip](https://github.com/TBM13/Samsung-Camera-Experiments/files/14003028/S20lte.zip)

SM-G980F aka s20lte

**Comment by TBM13** [comment]
The lib you sent in the `lib64` folder is a 32-bit lib. Can you double check you sent the correct one?

**Comment by SusssyBakaLOL** [comment]
I apologize for the delay, i was sending it on someone else's behalf and they didnt send me the proper files.
Here they are: 
[Libs-S20-lte.zip](https://github.com/TBM13/Samsung-Camera-Experiments/files/14132728/Libs-S20-lte.zip)

**Comment by TBM13** [comment]
The script can already patch both libs without any apparent issue.
